name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#    - name: Install dependencies
#     run: sudo apt-get install -y python3-paramiko

    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Update Build Info
      env:
        FORK_ID: ${{ vars.FORK_ID }}
      run: Tools/gen_build_info.py

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        cp release/*.zip "release/${{ github.sha }}"

    - name: Upload files to centcomm
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --ignore-existing
        path: "release/${{ github.sha }}"
        remote_path: ${{ secrets.BUILDS_FOLDER }}
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSHKEY }}
        remote_port: ${{ secrets.PORT }}

    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key:  ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: node ~/ss14/manifest_generation/create-manifest.js -fork theta -id ${{ github.sha }}
