name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    # Corvax-Secrets-Start
    - name: Setup secrets
      env:
        SSH_KEY: ${{ secrets.SECRETS_PRIVATE_KEY }}
      if: ${{ env.SSH_KEY != '' }}
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SECRETS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "HOST *" > ~/.ssh/config
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        git -c submodule.Secrets.update=checkout submodule update --init
      # Corvax-Secrets-End
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.100

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Package client
      run: |
        Tools/package_server_build.py -p win-x64 linux-x64 osx-x64 linux-arm64
        Tools/package_client_build.py

    - name: Update Build Info
      run: Tools/gen_build_info.py

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        cp release/*.zip "release/${{ github.sha }}"

    - name: Upload files to centcomm
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --ignore-existing
        path: "release/${{ github.sha }}"
        remote_path: ${{ secrets.BUILDS_FOLDER }}
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSHKEY }}
        remote_port: ${{ secrets.PORT }}
  
#    - name: Update release version
#      uses: garygrossgarten/github-action-scp@release
#      with:
#        local: release/SS14.Client.zip
#        remote: release/SS14.Client.zip
#        host: ${{ secrets.HOST }}
#        port: ${{ secrets.PORT }}
#        username: ${{ secrets.USERNAME }}
#        privateKey: ${{ secrets.SSHKEY }}

    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key:  ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: node ~/scripts/create-manifest.js -fork theta -id ${{ github.sha }}
